QuanLyNhanSu/QuanLyNhanSu.Web/Controllers/DonViController.cs
using System.Linq;
using System.Threading.Tasks;
using QuanLyNhanSu.Common.Constants;
using QuanLyNhanSu.Data.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using QuanLyNhanSu.Data.DataService;
using System;
using Newtonsoft.Json;
using System.Text;
using System.Collections.Generic;
using System.Net.Http.Headers;

namespace QuanLyNhanSu.Web.Controllers
{
    public class DonViController : BaseController
    {
        public const string BASE_URL_API = "https://localhost:5001";
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;

        public DonViController(IHttpClientFactory httpClientFactory,
                         IHttpContextAccessor httpContextAccessor,
                          IConfiguration configuration)
        {
            _httpContextAccessor = httpContextAccessor;
            _configuration = configuration;
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration["BaseAddress"]);
                HttpResponseMessage response = Task.Run(async () => await client.GetAsync("/api/DonVi/GetAllRecords")).Result;

                var test = response.Content.ReadAsStringAsync().Result;
                var listdata = new List<QuanLyNhanSu.Model.Entities.DonVi>();

                if (response.IsSuccessStatusCode)
                {
                    listdata = JsonConvert.DeserializeObject<List<QuanLyNhanSu.Model.Entities.DonVi>>(test.ToString());

                    return PartialView("_PartialData", listdata);
                }

                return PartialView("_PartialData", listdata);

            }
            catch (Exception ex)
            {
                return PartialView("_PartialData", null);
            }
        }

        public async Task<JsonResult> ThemMoi(string name, string mota="")
        {
            try
            {
                if (name.Length == 0)
                {
                    return Json("Không được để trống");
                }
                if (mota == null)
                {
                    mota = "";
                }

                QuanLyNhanSu.Model.Entities.DonVi obj = new QuanLyNhanSu.Model.Entities.DonVi();
                obj.TenDonVi = name.Trim();
                obj.MoTa = mota.Trim();

                var sessions = _httpContextAccessor
               .HttpContext
               .Session
               .GetString(SystemConstants.AppSettings.Token);

                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration[SystemConstants.AppSettings.BaseAddress]);
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", sessions);
                var requestContent = new MultipartFormDataContent();
                requestContent.Add(new StringContent("123"), "MaDonVi");
                requestContent.Add(new StringContent(obj.TenDonVi.ToString()), "TenDonVi");
                requestContent.Add(new StringContent(obj.MoTa.ToString()), "MoTa");
                string url = string.Empty;
                url = BASE_URL_API + "/api/DonVi";
                var response = await client.PostAsync(url, requestContent);

                return Json("OK");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi thêm mới: " + ex.Message;
                return Json("Lỗi thêm mới");
            }
        }

        public async Task<JsonResult> Sua(int id, string ma, string name, string mota="")
        {
            try
            {
                if (name.Length == 0 || ma.Length == 0)
                {
                    return Json("Không được để trống");
                }
                if (mota == null)
                {
                    mota = "";
                }

                QuanLyNhanSu.Model.Entities.DonVi obj = new QuanLyNhanSu.Model.Entities.DonVi();
                obj.Id = id;
                obj.MaDonVi = ma.Trim();
                obj.TenDonVi = name.Trim();
                obj.MoTa = mota.Trim();

                var sessions = _httpContextAccessor
               .HttpContext
               .Session
               .GetString(SystemConstants.AppSettings.Token);

                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration[SystemConstants.AppSettings.BaseAddress]);
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", sessions);
                var requestContent = new MultipartFormDataContent();
                requestContent.Add(new StringContent(obj.MaDonVi.ToString()), "MaDonVi");
                requestContent.Add(new StringContent(obj.TenDonVi.ToString()), "TenDonVi");
                requestContent.Add(new StringContent(obj.MoTa.ToString()), "MoTa");
                //      var response = await client.PutAsync($"​/api​/DonVi/" + obj.Id, requestContent);
                string url = string.Empty;
                url = BASE_URL_API + "/api/DonVi/" + obj.Id;
                HttpResponseMessage response = Task.Run(async () => await client.PutAsync(url, requestContent)).Result;

                return Json("OK");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi cập nhật: " + ex.Message;
                return Json("Lỗi cập nhật");
            }
        }
        public async Task<JsonResult> Xoa(long id)
        {
            try
            {
                var sessions = _httpContextAccessor
                               .HttpContext
                               .Session
                               .GetString(SystemConstants.AppSettings.Token);
                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration["BaseAddress"]);
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", sessions);
                string url = string.Empty;
                url = BASE_URL_API + "/api/DonVi/" + id;
                HttpResponseMessage response = await client.DeleteAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    return Json("OK");
                }
                return Json("Error");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi xóa: " + ex.Message;
                return Json("Lỗi xóa");
            }
        }

    }
}

QuanLyNhanSu/QuanLyNhanSu.Web/Views/DonVi/Index.cshtml
@{ ViewData["Title"] = "Quản lý Đơn vị"; }
@section Scripts{
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Danh mục Đơn vị
        </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="breadcrumb-item active">Danh mục Đơn vị</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <!-- /.modal -->
                    <!-- /.box-header -->
                    <div class="">
                        <div class="row" style="margin:10px 15px;float:right">
                            <button type="button" data-toggle="modal" data-target="#modeladd" class="btn btn-success">
                                <i class="fa fa-plus" title="thêm mới"></i>
                                Thêm mới
                            </button>
                        </div>
                    </div>
                    <div class="box-body" id="_partialData">

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<div class="modal fade" id="modeldetail" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title_naptien">Sửa</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="IdEdit" hidden value="" />
                <div class="form-group">
                    <h5>Mã Đơn vị<span class="text-danger">*</span></h5>
                    <div class="controls">
                        <input type="text" readonly class="form-control" id="ma_edit" name="ma_edit" required="required"> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <h5>Tên Đơn vị<span class="text-danger">*</span></h5>
                    <div class="controls">
                        <input type="text" class="form-control" id="name_edit" name="name_edit" required="required"> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <h5>Mô tả<span class="text-danger"></span></h5>
                    <div class="controls">
                        <textarea type="text" class="form-control" rows="3" id="mota_edit" name="mota_edit"></textarea> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default btn-offmodel" data-dismiss="modal">Hủy</button>
                    <button type="button" id="btnEdit" class="btn btn-success" data-dismiss="modal">Sửa</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modeladd" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title_naptien">Thêm</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <h5>Tên Đơn vị<span class="text-danger">*</span></h5>
                    <div class="controls">
                        <input type="text" class="form-control" id="name_add" name="name_add" required="required"> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <h5>Mô tả<span class="text-danger"></span></h5>
                    <div class="controls">
                        <textarea type="text" class="form-control" rows="3" id="mota_add" name="mota_add"></textarea> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default btn-offmodel" data-dismiss="modal">Hủy</button>
                    <button type="button" id="btnAdd" class="btn btn-success" data-dismiss="modal">Thêm</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="modal fade" id="modeldelete" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Xóa cấu hình</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div class="form-group">
                        <center>
                            <input type="hidden" name="IdXoa" id="IdXoa" value="" />
                            <h3>Bạn có chăc muốn xóa?</h3>
                        </center>
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default btn-offmodel" data-dismiss="modal">Hủy</button>
                    <button type="button" id="btnXoa" class="btn btn-success" data-dismiss="modal">Xóa</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div id="divProcessing" style="position:fixed;top:0px; left:0px; height:100%;width :100%;text-align:center;
         background:#f5f5f5;
         opacity:0.5;
         z-index:999;
         position:absolute;
         left:0px;
         top :0px;
         cursor: wait; display:none">
    <img style="position: fixed;top: 45%;" src="~/Images/processing.gif" alt="" width="70" height="70" />
</div>

<script>
    $(document).ready(function () {
        LoadListData();
    });

    function LoadListData() {
        $('#divProcessing').show();
           $.ajax({
            url: '@Url.Action("GetData", "DonVi")',
            type: "GET",
               dataType: "html",
               success: function (data) {
                   $('#_partialData').html('');
                   $('#_partialData').html(data);
                   $('#divProcessing').hide();
             },
             error: function (error) {
                 $('#divProcessing').hide();
                 console.log('lỗi load dữ liệu: ' + error.responseText);
             }
        });
    }
  function confirmremove(id) {
        $('#IdXoa').val(id);
    }
    function opendetail(id,ma, name, stt) {
        $('#IdEdit').val(id);
        $('#ma_edit').val(ma);
        $('#name_edit').val(name);
        $('#trangthai_edit').val(stt);        
    }
    $('#btnAdd').click(function () {
        var name = $('#name_add').val();
        var mota = $('#mota_add').val();
        if (name == "") {
            toastr.error('Không được để trống');
            return false;
        }
        $("#divProcessing").show();
                $.ajax({
                    url: '@Url.Action("ThemMoi", "DonVi")',
                    type: "get",
                    data: { name: name, mota: mota },
                    dataType: "json",
                    contentType: 'application/json',
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data == 'OK') {
                            toastr.success('Thêm mới thành công');
                            $('#name_add').val('');
                            LoadListData();
                        } else {
                            toastr.error(data);
                        }
                    },
                    error: function (err) {
                        //$("#divProcessing").show();
                        alert(err.statusText);
                    }
                });
    })
    $('#btnXoa').click(function () {
        var id = $('#IdXoa').val();
        $("#divProcessing").show();
                $.ajax({
                    url: '@Url.Action("Xoa", "DonVi")',
                    type: "get",
                    data: {id :id},
                    dataType: "json",
                    contentType: 'application/json',
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data == 'OK') {
                            toastr.success('Xóa thành công');
                            LoadListData();
                        } else {
                            toastr.error(data);
                        }
                    },
                    error: function (err) {
                        //$("#divProcessing").show();
                        alert(err.statusText);
                    }
                });

    })
    $('#btnEdit').click(function () {
        var id=$('#IdEdit').val();
        var name = $('#name_edit').val();
        var ma = $('#ma_edit').val();
        var mota = $('#mota_edit').val();
        if (name == "" || ma=="") {
            toastr.error('Không được để trống');
            return false;
        }

        $("#divProcessing").show();
                $.ajax({
                    url: '@Url.Action("Sua", "DonVi")',
                    type: "get",
                    data: { id: id, ma: ma, name: name, mota: mota},
                    dataType: "json",
                    contentType: 'application/json',
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data == 'OK') {
                            toastr.success('Sửa thành công');
                            $('#IdEdit').val('');
                            $('#name_edit').val('');
                            LoadListData();
                        } else {
                            toastr.error(data);
                        }
                    },
                    error: function (err) {
                        //$("#divProcessing").show();
                        alert(err.statusText);
                    }
                });

    })
</script>

QuanLyNhanSu/QuanLyNhanSu.Web/Views/DonVi/_PartialData.cshtml
@using QuanLyNhanSu.Model.Entities
@model List<DonVi>

<script src="~/cryptoadmin/crypto-currency-admin/assets/vendor_components/datatables.net/js/jquery.dataTables.min.js"></script>

<div class="table-responsive">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th style="text-align:center" width="20%">Mã Đơn vị</th>
                <th style="text-align:center">Tên Đơn vị</th>
                <th style="text-align:center">Mô tả</th>
                <th style="text-align:center">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaDonVi</td>
                        <td>@item.TenDonVi</td>
                        <td>@item.MoTa</td>
                        <td style="text-align:center">
                            <button type="button" onclick="opendetail('@item.Id', '@item.MaDonVi', '@item.TenDonVi', '@item.MoTa')" class="btn btn-round btn-info" data-toggle="modal" data-target="#modeldetail" title="Sửa">Sửa</button>
                            <button type="button" onclick="confirmremove(@item.Id)" class="btn btn-round btn-danger" data-toggle="modal" data-target="#modeldelete" title="Xóa">Xóa</button>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>
<script>
    $('#example1').dataTable({
        "pageLength": 10,
        "stateSave": true,
        "order": [],
    });
</script>