QuanLyNhanSu/QuanLyNhanSu.Web/Controllers/NhanVien_TSCPController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using QuanLyNhanSu.Common.Constants;
using QuanLyNhanSu.Data.ViewModel;
using QuanLyNhanSu.Model.Entities;
using QuanLyNhanSu.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace QuanLyNhanSu.Web.Controllers
{
    public class NhanVien_TSCPController : BaseController
    {
        public const string BASE_URL_API = "https://localhost:5001";
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;

        public NhanVien_TSCPController(IHttpClientFactory httpClientFactory,
                         IHttpContextAccessor httpContextAccessor,
                          IConfiguration configuration)
        {
            _httpContextAccessor = httpContextAccessor;
            _configuration = configuration;
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult GetData()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration["BaseAddress"]);
                HttpResponseMessage response = Task.Run(async () => await client.GetAsync("/api/NhanVien_TSCP/GetAllDetailNhanVien_TSCP")).Result;

                var test = response.Content.ReadAsStringAsync().Result;
                var listdata = new List<NhanVien_TSCP_DetailViewModel>();

                if (response.IsSuccessStatusCode)
                {
                    listdata = JsonConvert.DeserializeObject<List<NhanVien_TSCP_DetailViewModel>>(test.ToString());

                    return PartialView("_PartialData", listdata);
                }

                return PartialView("_PartialData", listdata);

            }
            catch (Exception ex)
            {
                return PartialView("_PartialData", null);
            }
        }
        public ActionResult GetListTSCP(int id)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration["BaseAddress"]);
                HttpResponseMessage response = Task.Run(async () => await client.GetAsync("/api/NhanVien_TSCP/GetDetailNhanVien_TSCP/"+id)).Result;

                var data = response.Content.ReadAsStringAsync().Result;
                var listdata = new List<TaiSanCapPhatViewModel>();

                HttpResponseMessage response1 = Task.Run(async () => await client.GetAsync("/api/DM_TaiSanCapPhat/GetAllRecords")).Result;
                var data1 = response1.Content.ReadAsStringAsync().Result;
                var lst_ts = new List<QuanLyNhanSu.Model.Entities.DM_TaiSanCapPhat>();
                if (response.IsSuccessStatusCode)
                {
                    lst_ts = JsonConvert.DeserializeObject<List<QuanLyNhanSu.Model.Entities.DM_TaiSanCapPhat>>(data1.ToString());
                }

                if (response.IsSuccessStatusCode)
                {
                    NhanVien_TSCP_DetailViewModel csdl = JsonConvert.DeserializeObject<NhanVien_TSCP_DetailViewModel>(data.ToString());
                    foreach (var item in lst_ts)
                    {
                        var obj = new TaiSanCapPhatViewModel();
                        obj.Id = item.Id;
                        obj.MaTaiSanCapPhat = item.MaTaiSanCapPhat;
                        obj.TenTaiSanCapPhat = item.TenTaiSanCapPhat;
                        obj.MoTa = item.MoTa;
                        obj.SoLuongConLai = item.SoLuong;
                        obj.SoLuong = 0;
                        if (csdl.dM_TaiSanCapPhats!=null) {
                            foreach (var itemDaMuon in csdl.dM_TaiSanCapPhats)
                            {
                                if (itemDaMuon.Id == item.Id)
                                {
                                    obj.SoLuong = itemDaMuon.SoLuong;
                                }
                            }
                        }                        
                        listdata.Add(obj);
                    }
                    return PartialView("_PartialDataDMTSCP", listdata);
                }

                return PartialView("_PartialDataDMTSCP", listdata);

            }
            catch (Exception ex)
            {
                return PartialView("_PartialDataDMTSCP", null);
            }
        }

        public async Task<JsonResult> CapNhat(int id, string id_tscp, string noidung,string type)
        {
            try
            {
                if (noidung==null)
                {
                    noidung = "";
                }
                var nguoitao = User != null ? User.Identity.Name : "Admin";

                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri(_configuration[SystemConstants.AppSettings.BaseAddress]);

                HttpResponseMessage rp = Task.Run(async () => await client.GetAsync("/api/DM_ThamSoHeThong/" + id)).Result;
                var result_obj = rp.Content.ReadAsStringAsync().Result;
               
                var sessions = _httpContextAccessor
               .HttpContext
               .Session
               .GetString(SystemConstants.AppSettings.Token);

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", sessions);
                var requestContent = new MultipartFormDataContent();
                requestContent.Add(new StringContent(id_tscp.ToString().Trim()), "IdTSCP");
                requestContent.Add(new StringContent(SystemConstants.Web.TRANGTHAI_NHANVIEN_TSCP_DANGCHOMUON.ToString().Trim()), "TrangThai");
                requestContent.Add(new StringContent(noidung.ToString().Trim()), "NoiDung");
                string url = string.Empty;
                if (type.Equals("Create"))
                {
                    requestContent.Add(new StringContent(id.ToString().Trim()), "IdNhanVien");
                    requestContent.Add(new StringContent(nguoitao), "NguoiTao");
                    url = BASE_URL_API + "/api/NhanVien_TSCP/Create";
                    HttpResponseMessage response = Task.Run(async () => await client.PostAsync(url, requestContent)).Result;
                }
                else
                {
                    requestContent.Add(new StringContent(id.ToString().Trim()), "Id");
                    requestContent.Add(new StringContent(nguoitao), "NguoiCapNhat");
                    url = BASE_URL_API + "/api/NhanVien_TSCP/Update";
                    HttpResponseMessage response = Task.Run(async () => await client.PutAsync(url, requestContent)).Result;
                }              

                return Json("OK");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi cập nhật: " + ex.Message;
                return Json("Lỗi cập nhật");
            }
        }
    }
}

QuanLyNhanSu/QuanLyNhanSu.Web/Views/NhanVien_TSCP/Index.cshtml
@{ ViewData["Title"] = "Cấp phát tài sản cho nhân viên"; }
@section Scripts{
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Cấp phát tài sản cho nhân viên
        </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="breadcrumb-item active">Cấp phát tài sản cho nhân viên</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <!-- /.modal -->
                    <!-- /.box-header -->
                    <div class="box-body" id="_partialData">

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>


<div class="modal fade" id="modeldetail" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title">Cấp phát tài sản</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <input hidden id="Id_edit" name="Id_edit" />
                <input hidden id="ObjId_edit" name="ObjId_edit" />
                <input hidden id="type" name="type" />
                <div class="form-group">
                    <h5>Nhân viên<span class="text-danger">*</span></h5>
                    <div class="controls">
                        <input type="text" disabled class="form-control" id="ten_nv" name="ten_nv" readonly> <div class="help-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <h5>Nội dung(Ghi chú)<span class="text-danger"></span></h5>
                    <div class="controls">
                        <textarea type="text" rows="3" class="form-control" id="noidung" name="noidung"></textarea> <div class="help-block"></div>
                    </div>
                </div>
                <div id="lst_tscp">

                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default btn-offmodel" data-dismiss="modal">Hủy</button>
                    <button type="button" id="btnEdit" class="btn btn-success" data-dismiss="modal">Cập nhật</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<!-- /.content-wrapper -->
<div id="divProcessing" style="position:fixed;top:0px; left:0px; height:100%;width :100%;text-align:center;
         background:#f5f5f5;
         opacity:0.5;
         z-index:999;
         position:absolute;
         left:0px;
         top :0px;
         cursor: wait; display:none">
    <img style="position: fixed;top: 45%;" src="~/Images/processing.gif" alt="" width="70" height="70" />
</div>

<script>
    $(document).ready(function () {
        LoadListData();
    });
    function opendetail(id, tennv, noidung,objId,type) {
        $('#noidung').val(noidung);
        $('#type').val(type);
        $('#ten_nv').val(tennv);
        $('#Id_edit').val(id);
        $('#ObjId_edit').val(objId);
        $('#divProcessing').show();
        $.ajax({
            url: '@Url.Action("GetListTSCP", "NhanVien_TSCP")',
            type: "GET",
            dataType: "html",
            data: {id:id},
            success: function (data) {
                $('#lst_tscp').html('');
                $('#lst_tscp').html(data);
                $('#divProcessing').hide();
             },
             error: function (error) {
                 $('#divProcessing').hide();
                 console.log('lỗi load dữ liệu: ' + error.responseText);
             }
        });
    }
    function LoadListData() {
        $('#divProcessing').show();
           $.ajax({
            url: '@Url.Action("GetData", "NhanVien_TSCP")',
            type: "GET",
               dataType: "html",
               success: function (data) {
                   $('#_partialData').html('');
                   $('#_partialData').html(data);
                   $('#divProcessing').hide();
             },
             error: function (error) {
                 $('#divProcessing').hide();
                 console.log('lỗi load dữ liệu: ' + error.responseText);
             }
        });
    }
    $('#btnEdit').click(function () {
        var type = $('#type').val();
        if (type == 'Create') {
            var id = $('#Id_edit').val();
        }
        else {
            var id = $('#ObjId_edit').val();
        }
        var noidung = $('#noidung').val();
        var id_tscp = "";
        var lstcheckbox = $("input[type='checkbox'].tscp_id:checked");
        var check = true;
        lstcheckbox.each(function () {
            var soluong = 0;
            var namediv = 'tscp_sl_'+$(this).attr('data');
            soluong = $('#' + namediv).val();
            if (soluong==0) {
                check = false;
                return false;
            }
            id_tscp += $(this).val() +':'+soluong +';';
        });
        if (!check) {
            toastr.error("Số lượng không được để trống");
            return false;
        }
        if (id == '') {
            toastr.error('Lỗi');
            return false;
        }
        id_tscp = id_tscp.substring(0, id_tscp.length - 1);
        
        $("#divProcessing").show();
                $.ajax({
                    url: '@Url.Action("CapNhat", "NhanVien_TSCP")',
                    type: "get",
                    data: { id: id, id_tscp: id_tscp, noidung: noidung, type: type},
                    dataType: "json",
                    contentType: 'application/json',
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data == 'OK') {
                            toastr.success('Sửa thành công');
                            LoadListData();
                        } else {
                            toastr.error(data);
                        }
                    },
                    error: function (err) {
                        //$("#divProcessing").show();
                        alert(err.statusText);
                    }
                });

    })
</script>

QuanLyNhanSu/QuanLyNhanSu.Web/Views/NhanVien_TSCP/_PartialData.cshtml
@using QuanLyNhanSu.Data.ViewModel;
@using QuanLyNhanSu.Common.Constants;
@model List<NhanVien_TSCP_DetailViewModel>

<script src="~/cryptoadmin/crypto-currency-admin/assets/vendor_components/datatables.net/js/jquery.dataTables.min.js"></script>

<div class="table-responsive">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th style="text-align:center" width="20%">Tên nhân viên</th>
                <th style="text-align:center">Tài sản cấp phát</th>
                <th style="text-align:center">Ngày cấp</th>
                <th style="text-align:center">Trạng thái</th>
                <th style="text-align:center">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.nhanVien.Ten</td>
                        @if (item.dM_TaiSanCapPhats.Count > 0)
                        {
                            <td>
                                @foreach (var tscp in item.dM_TaiSanCapPhats)
                                {
                                    <p>@tscp.MaTaiSanCapPhat - @tscp.TenTaiSanCapPhat - Số lượng : @tscp.SoLuong</p>
                                }
                            </td>
                            <td>@item.nhanVien_TSCP.NgayTao</td>

                            <td>
                                @if (item.nhanVien_TSCP.TrangThai == 1)
                                {
                                    <span>Đang cho mượn</span>
                                }
                                else if (item.nhanVien_TSCP.TrangThai == 0)
                                {
                                    <span>Đã trả</span>
                                }
                                else
                                {
                                    <span>Không xác định</span>
                                }
                            </td>
                            <td style="text-align:center">
                                <button type="button" onclick="opendetail('@item.nhanVien.Id', '@item.nhanVien.Ten (@item.nhanVien.IdCBNV)', '@item.nhanVien_TSCP.NoiDung','@item.nhanVien_TSCP.Id','Edit')" class="btn btn-round btn-info" data-toggle="modal" data-target="#modeldetail" title="Sửa">Cập nhật tài sản</button>
                            </td>
                        }
                        else
                        {
                            <td>
                                Chưa được cấp phát tài sản
                            </td>
                            <td></td>
                            <td></td>
                            <td style="text-align:center">
                                <button type="button" onclick="opendetail('@item.nhanVien.Id', '@item.nhanVien.Ten (@item.nhanVien.IdCBNV)', '@item.nhanVien_TSCP.NoiDung','@item.nhanVien_TSCP.Id','Create')" class="btn btn-round btn-warning" data-toggle="modal" data-target="#modeldetail" title="Sửa">Thêm tài sản</button>
                            </td>
                        }

                    </tr>

                }
            }
        </tbody>
    </table>
</div>
<script>
    $('#example1').dataTable({
        "pageLength": 10,
        "stateSave": true,
        "order": [],
    });
</script>

QuanLyNhanSu/QuanLyNhanSu.Web/Views/NhanVien_TSCP/_PartialDataDMTSCP.cshtml
@using QuanLyNhanSu.Model.Entities
@model List<TaiSanCapPhatViewModel>

<script src="~/cryptoadmin/crypto-currency-admin/assets/vendor_components/jquery/dist/jquery.js"></script>
<script src="~/cryptoadmin/crypto-currency-admin/assets/vendor_components/datatables.net/js/jquery.dataTables.min.js"></script>
<style>
    #example2 > tbody > tr > td {
        padding: 5px !important;
    }

    .tscp_id {
        opacity: 1 !important;
        position: initial !important;
    }
</style>

<div class="table-responsive">
    <table id="example2" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th></th>
                <th style="text-align:center" width="20%">Mã tài sản cấp phát</th>
                <th style="text-align:center">Tên tài sản cấp phát</th>
                <th style="text-align:center" width="20%">Số lượng</th>
                <th style="text-align:center">Mô tả</th>
                <th style="text-align:center">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {


                    <tr>
                        <td style="text-align:center">
                            @if (item.SoLuong != 0)
                            {
                                <input class="tscp_id" id="tscp_@item.Id" type="checkbox" data="@item.Id" checked="checked" value="@item.MaTaiSanCapPhat">
                            }
                            else
                            {
                                <input class="tscp_id" id="tscp_@item.Id" type="checkbox" data="@item.Id" value="@item.MaTaiSanCapPhat">
                            }
                        </td>
                        <td>@item.MaTaiSanCapPhat</td>
                        <td>@item.TenTaiSanCapPhat</td>
                        <td>
                            <input class="tscp_sl" id="tscp_sl_@item.Id" type="number" value="@item.SoLuong">
                        </td>
                        <td>@item.MoTa</td>
                        <td style="text-align:center">
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>

<script>
    var lstId = "";
    $('input[type=checkbox][class=tscp_id]').change(function () {
        if ($(this).is(":checked")) {
            $(this).attr("checked");
        }
    });
</script>
<script>
    $('#example2').dataTable({
        "pageLength": 10,
        "stateSave": true,
        "order": [],
    });
</script>